# Generated by Django 5.1.8 on 2025-04-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('type_annonce', models.CharField(choices=[('T', 'troc'), ('V', 'vente')], default='T', max_length=1)),
                ('user_contact', models.CharField(max_length=25)),
                ('article_image', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField()),
                ('categorie_article', models.CharField(max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='actif', max_length=10)),
                ('etiquette', models.CharField(max_length=9)),
                ('promotion_disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exigence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_exigence', models.TextField()),
                ('option_additionnelle', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
